version: '3.8'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-app
    ports:
      - "5001:5001"  # Flask app will be accessible on port 5000 inside the container
    volumes:
      - .:/home/ubuntu  # Mount local folder into the container
#    networks:
#      - app-network
    environment:
      - FLASK_ENV=development  # Set to "production" for production environment
#    depends_on:
#      - nginx

#  nginx:
#    image: nginx:latest
#    container_name: nginx
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your custom NGINX config file
#    ports:
#      - "80:80"  # NGINX will be exposed on port 80
#    networks:
#      - app-network

#networks:
#  app-network:
#    driver: bridge
